// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe4A6lwcp0cJgS5Sk9Qdf3iaIJU3QgNzM',
    appId: '1:997153268589:ios:f0b9d36a1200a1c642f064',
    messagingSenderId: '997153268589',
    projectId: 'fooddelivery-894ce',
    storageBucket: 'fooddelivery-894ce.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe4A6lwcp0cJgS5Sk9Qdf3iaIJU3QgNzM',
    appId: '1:997153268589:ios:f0b9d36a1200a1c642f064',
    messagingSenderId: '997153268589',
    projectId: 'fooddelivery-894ce',
    storageBucket: 'fooddelivery-894ce.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsrUvkW3XwAUjbJGle996SeTUxzOTSJwg',
    appId: '1:997153268589:web:d7aa84cfc65ec10b42f064',
    messagingSenderId: '997153268589',
    projectId: 'fooddelivery-894ce',
    authDomain: 'fooddelivery-894ce.firebaseapp.com',
    storageBucket: 'fooddelivery-894ce.appspot.com',
    measurementId: 'G-19NZWJF6B2',
  );
}
